version: 2
jobs:
  build:
    working_directory: ~/
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore Nuget
          command: dotnet restore
      - run:
          name: Build Solution
          command: dotnet build ./CsvFileConverter.sln
      - run:
          name: Run Test
          command: dotnet test InternProject.CsvFileConverter.XUnitTests
          
 workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master

