version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore Nuget
          command: dotnet restore
      - run:
          name: Build Solution
          command: dotnet build ./CsvFileConverter.sln
      - run:
          name: Run Test
          command: dotnet test InternProject.CsvFileConverter.XUnitTests
       
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
